TARGET = hello_multi_vag

SRCS = hello_multi_vag.c \
../VAG/hello.vag \
../VAG/poly.vag \
../VAG/0_come.vag \
../VAG/1_cuek.vag \
../VAG/2_erro.vag \
../VAG/3_hehe.vag \
../VAG/4_m4a1.vag \
../VAG/5_punc.vag \
../VAG/7_wron.vag \
../VAG/8_yooo.vag \

include ../common.mk 
