name: macOS build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Build mkpsxiso
        run: |
          wget https://github.com/Lameguy64/mkpsxiso/archive/refs/heads/master.zip -O ${{github.workspace}}/master.zip
          7z x ${{github.workspace}}/master.zip -o${{github.workspace}}/mkpsxiso
          mkdir ${{github.workspace}}/mkpsxiso/build
          ls -l ${{github.workspace}}/mkpsxiso
          cmake -DCMAKE_BUILD_TYPE=Release -S ${{github.workspace}}/mkpsxiso -B ${{github.workspace}}/mkpsxiso/build
          cmake --build ${{github.workspace}}/mkpsxiso/build
          echo "${{github.workspace}}/mkpsxiso/build" >> $GITHUB_PATH
      - name: Get converted libs
        run: |
          wget http://psx.arthus.net/sdk/Psy-Q/psyq-4.7-converted-full.7z
          7z x psyq-4.7-converted-full.7z -o./psyq
      - name: Make all
        run: make all
